controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xarm7_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    xarm7_posi_controller:
      type: forward_command_controller/ForwardCommandController

    autoserve_controller:
      type: diff_drive_controller/DiffDriveController

xarm7_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 1.0, goal: 0.01}
      joint2: {trajectory: 1.0, goal: 0.01}
      joint3: {trajectory: 1.0, goal: 0.01}
      joint4: {trajectory: 1.0, goal: 0.01}
      joint5: {trajectory: 1.0, goal: 0.01}
      joint6: {trajectory: 1.0, goal: 0.01}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0

xarm7_posi_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    interface_name: position

autoserve_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    left_wheel_names  : ['base2leftw']
    right_wheel_names : ['base2rightw']

    publish_rate: 30.0               # default: 50
    # pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    # twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation : 0.34
    wheel_radius : 0.05

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.1

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: false

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 5.0  # m/s
        min_velocity           : -5.0 # m/s
        has_acceleration_limits: false
        max_acceleration       : 5.0  # m/s^2
        min_acceleration       : -5.0 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 0.2  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 10.0  # rad/s
        min_velocity           : -10.0  # rad/s
        has_acceleration_limits: false
        max_acceleration       : 10.0  # rad/s^2
        min_acceleration       : -10.0   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 0.4  # rad/s^3